version: "3.9"

services:
  jogod:
    container_name:
      jogod
    restart: always
    build: ./JoGod/
    ports:
      - "80:5000"
    volumes:
      - ./JoGod/src:/app/src
    depends_on:
      - fabob
      - mongo
      - neo4j

  fabob:
    container_name:
      fabob
    restart: always
    build: ./FaBob/
    ports:
      - "5001:5001"
    volumes:
      - ./FaBob/src:/app/src
    depends_on:
      - mongo
      - neo4j

  mongo:
    image: mongo:4.2.0
    container_name:
      mongo_epicurien
    hostname: mongodb_epicurien
    environment:
      MONGO_INITDB_DATABASE: epicurien
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:4.2.0
    container_name:
      neo4j_epicurien
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG