version: "3.9"

services:
  jogod:
    container_name:
      jogod
    restart: always
    build: ./JoGod/
    ports:
      - "80:5000"
    volumes:
      - ./JoGod/src:/app/src
    depends_on:
      - fabob
      - mongo
      - neo4j
      - beaubrun

  fabob:
    container_name:
      fabob
    build: ./FaBob/
    ports:
      - "5001:5001"
    volumes:
      - ./FaBob/src:/app/src
    depends_on:
      - mongo
      - neo4j

  beaubrun:
    container_name:
      beaubrun
    restart: always
    build: ./BeauBrun
    ports:
      - "5002:5002"
    volumes:
      - ./BeauBrun/src:/app/src
    depends_on:
      - fabob
      - neo4j
      - mongo

  mongo:
    image: mongo:4.2.0
    container_name:
      mongo_epicurien
    hostname: mongodb_epicurien
    environment:
      MONGO_INITDB_DATABASE: epicurien
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:4.2.0
    container_name:
      neo4j_epicurien
    hostname: neo4j_epicurien
    volumes:
      - ./neo4j/plugins:/plugins
      - ./data/neo:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_logs_debug_level: DEBUG
    ports:
      - "7474:7474"
      - "7687:7687"
