name: jogod-ci
on:
  push:
    branches:
      - '**'
#    paths:
#      - 'JoGod/**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./JoGod/requirements.txt
      - name: Run Makefile test
        run: make test
      - name: Run formatter
        run: make check-format
      - name: Run Linters
        run: make lint